# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

demikernel:
  local_ipv4_addr: 10.2.14.1
  local_link_addr: "b8:ce:f6:7f:28:28"
raw_socket:
  linux_interface_name: "rdma2"
  xdp_interface_index: 0
dpdk:
  eal_init: ["", "-c", "0xff", "-n", "4", "-a", "86:00.0","--proc-type=auto"]
tcp_socket_options:
  keepalive:
    enabled: false
    time_millis: 0
    interval: 0
  linger:
    enabled: true
    time_seconds: 0
  nodelay: true
inetstack_config:
  mtu: 1500
  mss: 1500
  enable_jumbo_frames: false
  udp_checksum_offload: false
  tcp_checksum_offload: false
  arp_table:
    "1c:34:da:f3:99:c8": "10.2.14.254"
    "1c:34:da:f3:99:c8": "10.0.14.254"
  arp_request_retries: 5
  arp_request_timeout: 20
  arp_cache_ttl: 15

# vim: set tabstop=2 shiftwidth=2
